### ISSUE TITLE
[Suggestion] Pigsteel Tools, Weapons and Armour - more unique Iron Alternative

### ISSUE THREAD

**Issue by SpiderKolo** [ArshiaDPG/Pigsteel-Fabric#3]
Hey!

I like idea for your mod! It looks really nice and mechanic - while modified version of oxidization - fits really well to the game!
Have you considered perhaps making a set of tools and armour for this material which kept it's zombification attribute?

With more use tools would become more zombified and thus slower BUT dealt more damage and/or apply Hunger effect on players damaged by them?
Armour would protect less and less BUT reduce detection range from undead mobs?

And would NOT zombify in Nether - always keeping it in it's best conditions in it's native dimension... BUT possibly gain new uses if allowing zombification on said items?

Maybe Zombified tools could infect Piglins holding them and if players wears them - make them be afraid of player?

I think it would be really cool to have more interactions with Piglins, but also more toys to play with.

**Comment by SylisMC** [comment]
(To modmaker)
Im working on this for a personal project, if you want the textures and data entry information I'm more than happy to share it

**Comment by ArshiaDPG** [comment]
These sound like very interesting ideas, however we'd rather keep pigsteel under the iron equipment umbrella, like blackstone.
However, if you would like to add these features in a separate mod like an addon feel free to do so.
